version: 2

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install Pip
          command: 'apt install -y python3-pip'
      - run:
          name: Install Conan
          command: 'pip3 install conan'
      - run:
          name: Build
          command: './build.sh'
      - run:
          name: Run
          command: './run.sh && ./run.sh tests'      

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: 
                - master
                - dev
